### PR TITLE
 [V 0.1] simple script for Query UGA  API and  

### PR DESCRIPTION
**Pull request by simus81**
OK , i have made a PHP script who query UGA Marine Debris API and update a geoserver via WFS-T. you can easily set-it up for your geoserver or you can grant me access right , so i will do it.

don't hesitate to contact me by email

i also saw that maxrbaldwin started working with nodejs. I can quickly change my script to php->node  if you wish.

### CODE REVIEW

**Comment by metanomy** [comment]
1. Codebase: Yes, please change script to node.
2. I will provide you credentials to our geoserver via email. Please message me: cameron.hunt@metanomy.org.

**Comment by simus81** [comment]
i just when to push the javascript version of the script .Test are OK for
me.
don't hesitate to contact me if you have any trouble about it.

Regard
Simon
Torradou

2015-09-29 14:21 GMT+02:00 metanomy notifications@github.com:

**Comment by metanomy** [comment]
Simon,

Thanks for your work on this. Any recommendations on how to schedule this script to run to include new data?

**Comment by simus81** [comment]
Yes sure, but first, i wish claim my bounty if the issue is closed [50$]

**Comment by metanomy** [comment]
I closed the issue, so please claim

**Comment by simus81** [comment]
i think , a safe way to made this is to copy/past and make a version where you call  insertWFS instead of updateWFS

**Comment by simus81** [comment]
i think , a safe way to make this is to copy/past my script and make a version where you call insertWFS instead of updateWFS. you run insert in first and after you update. something like this if you run it every hour:
node UGAMarineQryinsert.js 3600 && node UGAMarineQryupdate.js 3600 
[not tested]

**Comment by simus81** [comment]
I also planned to work on this bounty in few week
https://www.bountysource.com/issues/26509281-integrate-noaa-gnome-as-a-wps-workflow

**Comment by metanomy** [comment]
@simus81 Would love to have you working on that challenge! Take a look at PyGnome (https://github.com/NOAA-ORR-ERD/PyGnome) and WebGnomeAPI (https://github.com/NOAA-ORR-ERD/WebGnomeAPI)

**Pull request merged**
